### ISSUE TITLE
Create KnapsackGenerator

### ISSUE THREAD

**Issue by mx-cifu** [mx-cifu/ComparingKnapsacksExperiment#9]

**Comment by jjemi8884** [comment]
## Start the generator
Need more information before proceeding
Will I be pasing a created node or do I make a node to pass to Max's test Generator?

**Comment by mx-cifu** [comment]
If I remember correctly,KnapsackGenerator will create Knapsack objects directly from the information out of the CSV file and pass those objects to whoever is upstream. As I'm typing this, I'm curious if Jackson said that Knapsack Generator would pass an ArrayList or something of those created nodes- or if those Knapsack objects get passed directly. 

We should consider having Jackson drop that diagram he made in Slack for us to see

**Comment by jjemi8884** [comment]
Okay so I took your branch and was able to create the Arraylist with your test object all filled up and ready to go. This will need more work but the CSV and test array is done.
